### ISSUE TITLE
虚拟化领域 有哪些 顶级期刊／会议？

### ISSUE THREAD

**Issue by liker12134** [liker12134/my-kernel-dev-environment#25]
1.  [A wiki for Calls For Papers](http://www.wikicfp.com/cfp/allcat) 
2. [中国计算机学会推荐国际学术会议和期刊目录](http://www.ccf.org.cn/ccf/contentcore/resource/download?ID=32826) 
- 计算机体系结构／高性能计算／存储系统；
- 计算机网络；
- 网络与信息安全；
- 软件工程/系统软件/程序设计语言；
- 数据库/数据挖掘/内容检索；
- 计算机科学理论；
- 计算机图形学与多媒体；
- 人工智能；
- 人机交互与普适计算；
- 交叉/新兴／综合等。

**Comment by liker12134** [comment]
虚拟化方向

- [ ] ICVAT @ International Conference on Virtualization Application and Technology

- [ ] VHPC @ Workshop on Virtualization in High-Performance Cloud Computing

- [ ] XDOM0 @ Workshop on Security and Dependability of Multi-Domain Infrastructures

- [ ] USENIX ATC @ International Conference on Virtualization Application and Technology

- [ ] CLOUD COMPUTING @ International Conference on Cloud Computing, GRIDs, and Virtualization

- [ ] IC2E @ IEEE International Conference on Cloud Engineering

- [ ] PROGNETS @ EAI International Conference on Programmable and Virtualized Networks

- [ ] FiCloud @ The IEEE International Conference on Future Internet of Things and Cloud

- [ ] SYSTOR @ ACM International Systems and Storage Conference

- [ ] Sec-VirtNet @ IEEE Workshop on Security in Virtualized Networks

- [ ] VT @ International Workshop on Virtualization Technologies in conjunction with Middleware

- [ ] CloudCom @ IEEE International Conference on Cloud Computing Technology and Science

- [ ] WIVOSCA @ Workshop on the Interaction amongst Virtualization, Operating Systems and Computer Architecture

- [ ] VTDC @ Virtualization Technologies in Distributed Computing

- [ ] HCCIEA @ International Workshop on Hybrid Cloud computing Infrastructure for E-Science application

**Comment by liker12134** [comment]
操作系统方向

- [ ] ASPLOS @ International Conference on Architectural Support for Programming Languages and Operating Systems

- [ ] EWILI @ Embedded Operating System Workshop

- [ ] ECBS @ European Conference on the Engineering of Computer Based Systems

- [ ] OSPERT @ Annual Workshop on Operating Systems Platforms for Embedded Real-Time Applications

- [ ] ROSS @ International Workshop on Runtime and Operating Systems for Supercomputers

- [ ] SYSTOR @ ACM International Systems and Storage Conference

- [ ] SEIoT @ Workshop on Security in equipment to the IoT

- [ ] HotOS @ Workshop on Hot Topics in Operating Systems

- [ ] VEE @ ACM SIGPLAN/SIGOPS International Conference on Virtual Execution Environments

- [ ] ARCS @ INTERNATIONAL CONFERENCE ON ARCHITECTURE OF COMPUTING SYSTEMS

- [ ] ICAITA @ International Conference on Advanced Information Technologies and Applications

- [ ] INFLOW @ Workshop on Interactions of NVM/Flash with Operating Systems and Workloads 

- [ ] EWiLi @ Embedded Operating System Workshop

- [ ] SBESC @ VI Brazilian Symposium on Computing Systems Engineering

- [ ] OSDI @ USENIX Symposium on Operating Systems Design and Implementation

- [ ] RST @ Special Issue on Reliable Software Technologies for Dependable Distributed Systems (Journal of System Architecture)

- [ ] NOSSDAV @ ACM SIGMM Workshop on Network and Operating Systems Support for Digital Audio and Video

- [ ] USENIX ATC @ USENIX Annual Technical Conference

**Comment by liker12134** [comment]
软件架构 Software Architecture

- [ ] IJSPTM @ International Journal of Security, Privacy and Trust Management

- [ ] Microservices @ Microservices - Special Issue at IEEE Software

- [ ] ISEC @ Innovations in Software Engineering Conference

- [ ] ISSA @ International workshop on Interplay of Security, Safety and System/Software Architecture

- [ ] SOFSEM @ International Conference on Current Trends in Theory and Practice of Computer Science

- [ ] SEFM @ International Conference on Software Engineering and Formal Methods

- [ ] ICSOFT @ International Conference on Software Technologies

- [ ] SOEN @ International Conference on Software Engineering

- [ ] ITPF @ International conference on Information Technology, Present and Future

- [ ] ACVI @ Architecture Centric Virtual Integration

**Comment by liker12134** [comment]
## 软件工程 / 系统软件 / 程序设计语言

### 学术期刊

1. TOPLAS @ ACM Transactions on Programming Languages & Systems

2. TOSEM @ ACM Transactions on Software Engineering Methodology

3. TSE @ IEEE Transactions on Software Engineering

**Comment by liker12134** [comment]
## 计算机体系结构 / 并行与分布计算 / 存储系统

### 学术期刊

- TOCS ／ TOC／ TPDS ／ TCAD ／ TOS

### 学术会议

- ASPLOS ／ FAST／HPCA ／ ISCA ／ MICRO ／SC ／USENIX ATC／PPoPP

**Comment by liker12134** [comment]
[The 26th ACM Symposium on Operating Systems Principles
October 28-31, 2017, Shanghai, China](http://sigops.org/sosp/sosp17/program.html)

**Comment by UvpStar** [comment]
* 学术会议
  * IPDPS 异构计算
  * NSDI  网络顶会
  * ASPLOS  计算机系统结构领域
  * ICPADS 分布式并行
  * ICDCS 分布式计算
  * OSDI ,USENIX 操作系统领域重要会议，侧重操作系统各方面的新型技术。
  * SOSP, 和 OSDI 交替举行，每两年一届，操作系统旗舰会议操作系统
  * SPAA, 算法和体系架构
  * SC 全球超级计算大会
* 厂商会议
  * Linaro
  * Microsoft
  * IBM
  * Gartner 
  * VMWare
  * Cloud Computing 
* 项目会议
  * XXX Con
    * Apache
  * XXX Summit
    * Arch
    * CNCF
  * XXX Forum 
    * KVM
  * 中国内核开发者大会（CLK 大会）
  * Cloud Open
  * MIT ILP [麻省理工学院全球产业联络计划](http://www.grinm.com/499-865-13641.aspx)
  * China CCF
* 安全峰会
  * FIRST
  * Troopers 
  * XXX安全峰会
  * Black Hat
  * XPwn 
  * OWASP
  * MOSEC
  * GeekPwn
  * KCon 
  * HITB
* 网络和通信学术界 Top1 的会议 SIGCOMM
* 信号处理、通信和计算三大领域 ICSPCC
* 测试峰会  STAREAST
* 讨论代码生成及优化技术
  * CGO
  * PPOPP
  * LLVM 
* FSE 大会是软件工程领域三大顶级会议（ICSE、FSE、ASE）之一
* 芯片设计工具以及嵌入式系统领域
  * Design Automation Conference（DAC）
  * NOCS
* Workshop
  * HOTCLOUD
  * ONS
  * OSCON
