### ISSUE TITLE
百度基础平台研发面试

### ISSUE THREAD

**Issue by xulike666** [liker12134/my-kernel-dev-environment#97]
[简历_徐黎科_百度(EN).pdf](https://github.com/liker12134/my-kernel-dev-environment/files/1370066/_._.EN.pdf)
[简历_徐黎科_百度(ZH).pdf](https://github.com/liker12134/my-kernel-dev-environment/files/1370067/_._.ZH.pdf)

http://talent.baidu.com/external/baidu/campus.html#/jobList

工作职责：
-设计、开发百度在线服务基础组件及平台，包括如下方向：大规模数据采集、压缩、传输系统；统一接入与防攻击系统、流量自动调度系统、分布式缓存、分布式数据库等

-设计、开发百度在线海量服务集群自动化管理与决策平台，包括如下方向：分布式监控系统、运维数据仓库与数据挖掘、认证与权限控制系统、变更系统、业务调度系统、网站速度优化平台等

-参与百度在线产品系统架构优化，提升效率、系统健壮性及可伸缩性

职位要求：
-对系统架构、后台技术有浓厚兴趣，热衷于追求技术极致与创新

-深刻理解数据结构和算法设计，精通C/C++、Java、PHP中至少一门编程语言

-了解linux/Unix操作系统原理、网络原理，熟练运用系统层支持应用开发

-优秀的分析问题和解决问题的能力，勇于解决难题

-强烈的上进心和求知欲，具备良好的沟通能力和团队合作精神

-符合以下条件之一优先考虑：分布式系统理论与实践、云计算相关组件经验、开源社区活跃、项目经验丰富

**Comment by liker12134** [comment]
面试官与招聘岗位是北京百度的，所以简单交流了城市意愿后离去，浪费感情，体验差。
